### ISSUE TITLE
Release v1.46.0 removed

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/bosh-package-cf-cli-release#13]
The already released version v1.46.0 was removed:
https://github.com/bosh-packages/cf-cli-release/commit/c06568002e66d2593c81f9272f3b88fadd659c14
It was also removed from bosh.io which broke some of the cf-deployment CI/CD jobs:
https://bosh.io/releases/github.com/bosh-packages/cf-cli-release?all=1
We could fix this, but we'd like to clarify why the release was removed. It would have been better to declare v1.46.0 as unusable and release v1.47.0.

Best Regards,

  Jochen.

**Comment by rkoster** [comment]
@reedr3 could you provide some more context on this change.

**Comment by ramonskie** [comment]
@ystros  made this commit so he probably kows some more
https://github.com/cloudfoundry/bosh-io-releases-index/commit/b80857ab38ca402bc502384e2a9f76e1a655c5a2

**Comment by reedr3** [comment]
Release 1.46.0 was a malformed release unintentionally created by an error in our release pipeline. Therefore we removed it so the correct release 1.45.0 could be used. If something like this happens in the future, we will instead declare it unusable and release a new version. Apologies for the disruption caused by this

**Comment by rkoster** [comment]
Thanks @reedr3 for the additional context.
